catand subcat
MOHAMMADALQUTAMI/FinalProject pull request #2
Opened 2023-08-13 16:16 UTC by OdaiAlqutami98

2023-08-15 15:29 UTC, IbrahimSwaiss requested changes

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/CategoryController.cs
> +        public async Task<IEnumerable<CategoryVM>> GetCategory()
rename this , it should be GetCategories

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/CategoryController.cs
> +         //   var Category = await _dbcontext.categorys.FindAsync(id);
remove commented code

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +            var subCategory = await _dbcontext.subcategories.Include(s => s.Category).ToListAsync();
rename subcategories to SubCategories

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +                    Id = s.Id,
this will set sub category id and name not the category - fix this

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +          [HttpGet("{id}")]
format the code

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +        var SubCategory = await _dbcontext.subcategories.SingleOrDefaultAsync(SubCategories => SubCategories.Id == id);
format the code

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +        var SubCategory = await _dbcontext.subcategories.SingleOrDefaultAsync(SubCategories => SubCategories.Id == id);
rename to subCategory

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +        public async Task<IActionResult> Post(CreateSubCategoryVM vM)
format the code

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +            var subcategory = new SubCategory
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +
remove empty lines

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +          [HttpPut]
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +        var Subcategory = await _dbcontext.subcategories.FindAsync(id);
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +      [HttpDelete("{id}")]
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +        var SubCategory  = await _dbcontext.subcategories.FindAsync(id);
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Controllers/SubCategoryController.cs
> +      //  _dbcontext.subcategories.Remove(SubCategory);
remove

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/Category.cs
> +    public class Category:BaseEntity
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/DbContext.cs
> +        public DbSet<Category>categorys {get;set;}
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/DbContext.cs
> +        public DbSet<SubCategory> subcategories {get;set;}
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/DbContext.cs
>              // builder.UseNpgsql("host=localhost ;port=5432; Database=FinalProject; username=postgres; password=xxxxxx ;IncludeErrorDetail=true;");
remove

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/SubCategory.cs
> +        public Category category { get; set; }
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Entity/SubCategory.cs
> +        public object Category { get; internal set; }
white this is object type, and why you're using internal setter?

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Models/SubCategory.cs
> +          public int Id { get; set; }
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Models/SubCategory.cs
> +        public string name { get; set; }
rename

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Models/SubCategory.cs
> +    public class SubCategory
should inherit from BaseEntity

2023-08-15 15:29 UTC, IbrahimSwaiss commented on Models/SubCategory.cs
> +          public int Id { get; set; }
remove Id

2023-08-15 15:29 UTC, IbrahimSwaiss commented on ViewModel/CategoryVM.cs
> +           public int Id { get; set; }
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on ViewModel/SubCategoryVM.cs
> +         public int Id { get; set; }
format

2023-08-15 15:29 UTC, IbrahimSwaiss commented on ViewModel/SubCategoryVM/CreateSubCategoryVM.cs
> +           public string Name { get; set; }
format

2023-08-16 00:59 UTC, OdaiAlqutami98 commented
Done

2023-08-17 15:28 UTC, merged